image: python:3.9

stages:
  - test
  - pages

pages:
  script:
    - pip install mkdocs mkdocstrings[python]
    - pip install mkdocs-material
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main  # Adjust if you deploy from a different branch

test:
  stage: test
  image: docker:latest
  services:
   - name: docker:dind
     
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - apk update
    - apk add just
    - just up; just test
  
