[project]
name = "pydelling"
version = "0.15.0"
description =  "Package providing a variety of utility methods for mathematical modelling"
requires-python = ">=3.10"
dependencies = [
    "alive-progress>=3.1.5",
    "charset-normalizer>=3.3.2",
    "dill>=0.3.8",
    "matplotlib>=3.9.2",
    "meshio>=5.3.5",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.34",
    "mkdocstrings>=0.26.1",
    "mpmath>=1.3.0",
    "natsort>=8.4.0",
    "numpy-stl>=3.1.2",
    "ofpp>=0.12",
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "paramiko>=3.5.0",
    "plotly>=5.24.1",
    "python-box>=7.2.0",
    "pyyaml>=6.0.2",
    "rich>=13.8.1",
    "rtree>=1.3.0",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
    "seaborn>=0.13.2",
    "setuptools>=75.1.0",
    "shapely>=2.0.6",
    "streamlit>=1.38.0",
    "tabulate>=0.9.0",
    "tqdm>=4.66.5",
    "trimesh>=0.0.1",
    #"vtk>=9.3.1; platform_system != 'Linux' and platform_machine != 'aarch64'",
    #"vtk>=9.3.1; platform_system == 'Linux' and platform_machine == 'aarch64'",
    "vtk>=9.3.1; platform_system != 'Linux' and platform_machine != 'arm64'",
    "xlrd>=2.0.1",
    "trimesh>=4.4.9",
    "h5py==3.11; platform_system != 'Linux' and platform_machine != 'aarch64'",
    "docker>=7.1.0",
]

[tool.hatch.build.targets."pydelling"]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
