"""
find_root_example.py
====================
Finds a root of scalar functions of one, two and three arguments with
find_root, starting from a point generated by a seed.
"""
import numpy as np
from pydelling.utils.root_finding_solver import find_root

# 1D: x^2 - 2 = 0, starting point from a standard normal (no bounds)
result = find_root(lambda x: x**2 - 2, seed=42)
print(f"1D  x0={result.x0}  root={result.x}  f={result.value:.2e}  iter={result.n_iter}  converged={result.converged}")

# 1D with analytical derivative and starting point sampled in [0, 5]
result = find_root(lambda x: np.cos(x) - x, seed=1, bounds=[(0, 5)], fprime=lambda x: -np.sin(x) - 1)
print(f"1D' x0={result.x0}  root={result.x}  f={result.value:.2e}  iter={result.n_iter}  converged={result.converged}")

# 2D: unit circle, the root found is one point of the circle
result = find_root(lambda x, y: x**2 + y**2 - 1, seed=0, bounds=[(-2, 2), (-2, 2)])
print(f"2D  x0={result.x0}  root={result.x}  |root|={np.linalg.norm(result.x):.6f}  converged={result.converged}")

# 3D: sphere of radius 2
result = find_root(lambda x, y, z: x**2 + y**2 + z**2 - 4, seed=3)
print(f"3D  x0={result.x0}  root={result.x}  |root|={np.linalg.norm(result.x):.6f}  converged={result.converged}")

# Different seeds give different starting points, and possibly different roots
for seed in range(4):
    result = find_root(lambda x: x**2 - 2, seed=seed, bounds=[(-3, 3)])
    print(f"seed={seed}  x0={result.x0[0]: .4f}  root={result.x[0]: .6f}")

# No real root: the solver stops without converging
result = find_root(lambda x: x**2 + 1, seed=42)
print(f"No root  converged={result.converged}  x={result.x}  f={result.value:.4f}")
