"""
This class can be inherited to create new GiD objects
It stores different GiD objects and generates batch files to generate the geometry automatically on GiD


"""

from __future__ import annotations

import functools
import logging

from .line import Line
from .point import Point
from .surface import Surface
from ._abstract_fit_object import _AbstractGidObject

logger = logging.getLogger(__name__)
from typing import Union, List

class GidObject(object):
    """Base container for generating GiD geometry command pipelines.

    Category: GID preprocessing.
    Tags: gid, geometry, pipeline, batch-commands.
    Use when: an MCP agent needs to understand how pydelling stores points,
        lines, surfaces, volumes, and generated GiD batch commands.
    """

    def __init__(self, *args, **kwargs):
        """Initialize in-memory containers for GiD pipeline construction.

        Args:
            *args (Any): Positional initialization arguments reserved for subclasses.
            **kwargs (Any): Keyword initialization arguments reserved for subclasses.
        """
        self.batch_commands = ''
        self.points = []
        self.lines = []
        self.surfaces = []
        self.volumes = []
        self.n_points = 1
        self.n_lines = 1
        self.n_surfaces = 1
        self.n_volumes = 1
        self.pipeline = []
        # self.set_up(*args, **kwargs)

    def construct(self, *args, **kwargs):
        """Build the pipeline steps for this object.

        Args:
            *args (Any): Positional arguments used by subclass implementations.
            **kwargs (Any): Keyword arguments used by subclass implementations.
        """
        pass

    def set_up(self, *args, **kwargs):
        """
        This method is expected to be changed by the user and it is called when the object is initialized

        Args:
            *args (Any): Positional setup arguments.
            **kwargs (Any): Keyword setup arguments.
        """

    def add(self, objects: Union[List[_AbstractGidObject], _AbstractGidObject, GidObject]):
        """
        Adds an object of type AbstractGidObject to the current GidObject instance depending on its type

        Args:
            objects (Union[List[_AbstractGidObject], _AbstractGidObject, GidObject]): Object or collection of objects to append to the pipeline.
        """
        if not isinstance(objects, list):
            objects = [objects]

        for obj in objects:
            assert isinstance(obj, _AbstractGidObject) or isinstance(obj, GidObject), 'The given object must be a Point, Line, Surface, Volume or another GidObject'
            if isinstance(obj, Point):
                self.pipeline.append({'add': obj})

            if isinstance(obj, Line):
                self.pipeline.append({'add': obj})

            if isinstance(obj, Surface):
                self.pipeline.append({'add': obj})

            if isinstance(obj, GidObject):
                self.import_gidobject(obj)

    def extrude(self, obj: Union[_AbstractGidObject, GidObject], start_point: Point, end_point: Point, end_object='Volumes'):
        """Append an extrusion operation to the pipeline.

        Args:
            obj (Union[_AbstractGidObject, GidObject]): Source object to extrude.
            start_point (Point): Start point for the extrusion vector.
            end_point (Point): End point for the extrusion vector.
            end_object (str): GiD target object type generated by extrusion.
        """
        assert isinstance(obj, Surface), 'Only surfaces can be extruded for now'
        self.pipeline.append({'extrude': obj, 'kwargs': {'start_point': start_point, 'end_point': end_point, 'end_object': end_object}})

    def join(self, point_1: Point, point_2: Point):
        """Create and add a line connecting two points.

        Args:
            point_1 (Point): First point.
            point_2 (Point): Second point.
        """
        join_line: Line = Line(point_1, point_2)
        self.add(join_line)

    def import_gidobject(self, gidobject):
        """Merge another GiD object's pipeline into this one.

        Args:
            gidobject (GidObject): Source GiD object to import.
        """
        gidobject.construct()
        self.pipeline += gidobject.pipeline

    def run(self, filename='gid_batch.bch', add_escape=False, internal=False):
        """
        Processes the construct method and generates the bash file

        Args:
            filename (str): Output GiD batch filename.
            add_escape (bool): Whether to append escape commands after each step.
            internal (bool): Whether to return commands instead of writing to disk.
        """
        logger.info('Processing GidObject by runnning the "construct()" method')
        self.construct()  # Generates the pipeline
        for step in self.pipeline:
            keys = list(step.keys())
            step_type = keys[0]
            if step.get('internal'):
                method = getattr(self, step_type)
            else:
                method = getattr(step[step_type], step_type)
            if add_escape:
                method = self.add_escape(method)
            self.batch_commands += method(*step.get('args', {}), **step.get('kwargs', {}))

        self.batch_commands += 'escape'
        if internal:
            return self.batch_commands
        else:
            with open(filename, 'w') as write_file:
                write_file.write(self.batch_commands)


    @staticmethod
    def add_escape(func):
        """Wrap a pipeline writer function to append an escape command.

        Args:
            func (Callable): Function that returns GiD batch commands.
        """
        @functools.wraps(func)
        def decorator(*args, **kwargs):
            func_return = func(*args, **kwargs)
            func_return += 'escape\n'
            return func_return
        return decorator
