"""Auto-generate API reference pages for mkdocstrings."""

from pathlib import Path
import tomllib

import mkdocs_gen_files


nav = mkdocs_gen_files.Nav()
package_modules: dict[str, list[Path]] = {}

src = Path("pydelling")
pyproject = Path("pyproject.toml")


def read_project_version() -> str:
    """Read project version from pyproject.toml."""
    with pyproject.open("rb") as fd:
        data = tomllib.load(fd)
    return str(data.get("project", {}).get("version", ""))


def is_importable_module(relative_path: Path) -> bool:
    """Return True when all parent directories are Python packages."""
    for parent in relative_path.parents:
        if parent == Path("."):
            continue
        if not (src / parent / "__init__.py").exists():
            return False
    return True


for path in sorted(src.rglob("*.py")):
    relative = path.relative_to(src)

    # Skip test modules and private modules/packages.
    if "tests" in relative.parts:
        continue
    if any(part.startswith("_") and part != "__init__.py" for part in relative.parts):
        continue
    if not is_importable_module(relative):
        continue

    module_parts = list(relative.with_suffix("").parts)
    if module_parts[-1] == "__init__":
        # Skip package pages to avoid duplicate symbols between package
        # exports (in __init__.py) and concrete module pages.
        continue

    doc_path = Path(*module_parts).with_suffix(".md")

    full_doc_path = Path("reference", doc_path)

    module_name = ".".join([src.name, *module_parts])

    nav[tuple(module_parts)] = doc_path.as_posix()
    package_modules.setdefault(module_parts[0], []).append(doc_path)

    with mkdocs_gen_files.open(full_doc_path, "w") as fd:
        fd.write(f"::: {module_name}\n")

# Create lightweight landing pages for package-level links without
# duplicating mkdocstrings objects from package __init__.py exports.
reference_index = Path("reference", "index.md")
with mkdocs_gen_files.open(reference_index, "w") as fd:
    fd.write("# API Modules\n\n")
    fd.write("Autogenerated API module pages.\n\n")
    for package in sorted(package_modules):
        fd.write(f"- [{package}]({package}/index.md)\n")

for package, docs_paths in sorted(package_modules.items()):
    package_index = Path("reference", package, "index.md")
    with mkdocs_gen_files.open(package_index, "w") as fd:
        fd.write(f"# {package}\n\n")
        fd.write("Autogenerated module pages:\n\n")
        for module_doc in sorted(docs_paths):
            # Skip the package index page itself.
            if module_doc == Path(package, "index.md"):
                continue
            title = module_doc.stem
            relative_link = module_doc.relative_to(package).as_posix()
            fd.write(f"- [{title}]({relative_link})\n")

summary_path = Path("reference", "SUMMARY.md")
with mkdocs_gen_files.open(summary_path, "w") as nav_file:
    nav_file.writelines(nav.build_literate_nav())

sidebar_version_js = Path("javascripts", "sidebar-version.js")
with mkdocs_gen_files.open(sidebar_version_js, "w") as fd:
    version = read_project_version()
    fd.write(f"window.__PYDELLING_VERSION__ = {version!r};\n")
